### ISSUE TITLE
Quay Security Scanner has detected 1 vulnerabilities

### ISSUE THREAD

**Issue by clyang82** [open-cluster-management/observability-e2e-test#146]
https://quay.io/repository/open-cluster-management/observability-e2e-test/manifest/sha256:e6b0c23e58bdcac6b726ff07fa2ac52f9c857189ffcd071af1e4235828e319fb?tab=vulnerabilities

**Comment by songleo** [comment]
image scans passed and close.

![image](https://user-images.githubusercontent.com/6408381/117278815-ad8c2300-ae93-11eb-95a7-dd597c90a0f9.png)
